#!/bin/bash
./auto-init
adb devices                 ## to make sure adb deamon is running
if [ ! -d "resources/android" ]; then
  ionic cordova platform add android
  ionic cordova resources
fi
ionic cordova run android
